# Generated by Django 4.0.4 on 2022-05-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerSource', models.CharField(db_index=True, max_length=200)),
                ('ownerId', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=50)),
                ('resolution', models.CharField(max_length=10)),
                ('lastModified', models.DateTimeField()),
                ('content', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='DrawingTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerSource', models.CharField(db_index=True, max_length=200)),
                ('ownerId', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('tool', models.CharField(max_length=200)),
                ('content', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='StudyTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerSource', models.CharField(db_index=True, max_length=200)),
                ('ownerId', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('content', models.JSONField()),
            ],
        ),
    ]
