# Generated by Django 4.0.4 on 2022-07-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_chart', '0002_alter_chart_id_alter_drawingtemplate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawingtemplate',
            name='content',
            field=models.JSONField(null=True),
        ),
    ]
